# SYNTHETIC: chats and messages are generated by the mock.
"""Pagination always terminates and assumes no ordering (T-010 M1/M2 are still open)."""

from __future__ import annotations

from typing import Any

import pytest

from app.avito_gateway import StopReason, paginate_chats, paginate_messages
from scripts.dev.avito_mock import SYNTHETIC_USER_ID, AvitoMock
from tests.avito.helpers import make_client

pytestmark = pytest.mark.anyio

U = SYNTHETIC_USER_ID
CHAT = "u2i-synthetic0000~chat"


async def _collect_ids(paginator) -> list[str]:
    ids: list[str] = []
    async for page in paginator:
        ids.extend(item.id for item in page.items)
    return ids


@pytest.mark.parametrize("order", ["newest_first", "oldest_first"])
async def test_messages_short_page_end_any_order(order: str) -> None:
    mock = AvitoMock.with_synthetic_data(n_chats=1, messages_per_chat=23, message_order=order)
    async with make_client(mock) as client:
        pager = paginate_messages(client, U, CHAT, limit=10)
        ids = await _collect_ids(pager)
    assert len(ids) == 23 and len(set(ids)) == 23
    assert pager.stop_reason is StopReason.SHORT_PAGE
    assert pager.pages == 3
    offsets = [int(r.query["offset"][0]) for r in mock.requests if r.endpoint == "messages_list"]
    assert offsets == [0, 10, 20]


async def test_exact_multiple_ends_on_empty_page() -> None:
    mock = AvitoMock.with_synthetic_data(n_chats=1, messages_per_chat=20)
    async with make_client(mock) as client:
        pager = paginate_messages(client, U, CHAT, limit=10)
        ids = await _collect_ids(pager)
    assert len(ids) == 20
    assert pager.stop_reason is StopReason.EMPTY_PAGE
    assert pager.pages == 3


async def test_short_page_stop_can_be_disabled() -> None:
    mock = AvitoMock.with_synthetic_data(n_chats=1, messages_per_chat=15)
    async with make_client(mock) as client:
        pager = paginate_messages(client, U, CHAT, limit=10, stop_on_short_page=False)
        ids = await _collect_ids(pager)
    assert len(ids) == 15
    assert pager.stop_reason is StopReason.EMPTY_PAGE


async def test_server_ignoring_offset_does_not_loop_forever() -> None:
    mock = AvitoMock.with_synthetic_data(n_chats=1, messages_per_chat=30, ignore_offset=True)
    async with make_client(mock) as client:
        pager = paginate_messages(client, U, CHAT, limit=10)
        await _collect_ids(pager)
    assert pager.stop_reason is StopReason.NO_NEW_IDS
    assert pager.pages == 2
    assert pager.duplicates == 10


async def test_offset_cap_stops_before_out_of_range_request() -> None:
    mock = AvitoMock.with_synthetic_data(n_chats=1, messages_per_chat=60)
    async with make_client(mock, offset_max=25) as client:
        pager = paginate_messages(client, U, CHAT, limit=10)
        ids = await _collect_ids(pager)
    assert pager.stop_reason is StopReason.OFFSET_CAP
    offsets = [int(r.query["offset"][0]) for r in mock.requests if r.endpoint == "messages_list"]
    assert offsets == [0, 10, 20]
    assert len(ids) == 30


async def test_default_offset_cap_is_spec_maximum() -> None:
    mock = AvitoMock.with_synthetic_data(n_chats=1, messages_per_chat=1200)
    async with make_client(mock) as client:
        pager = paginate_messages(client, U, CHAT, limit=99)
        ids = await _collect_ids(pager)
    assert pager.stop_reason is StopReason.OFFSET_CAP
    offsets = [int(r.query["offset"][0]) for r in mock.requests if r.endpoint == "messages_list"]
    assert max(offsets) <= 1000
    assert len(ids) == 99 * len(offsets) < 1200


@pytest.mark.parametrize(
    ("kwargs", "reason", "pages"),
    [({"max_pages": 2}, StopReason.MAX_PAGES, 2), ({"max_items": 25}, StopReason.MAX_ITEMS, 3)],
)
async def test_caller_caps(kwargs: dict[str, Any], reason: StopReason, pages: int) -> None:
    mock = AvitoMock.with_synthetic_data(n_chats=1, messages_per_chat=100)
    async with make_client(mock) as client:
        pager = paginate_messages(client, U, CHAT, limit=10, **kwargs)
        await _collect_ids(pager)
    assert pager.stop_reason is reason
    assert pager.pages == pages


async def test_sliding_offset_duplicates_are_counted_not_hidden() -> None:
    """A message arriving during a newest-first walk shifts every offset by one (T-010 M2)."""
    mock = AvitoMock.with_synthetic_data(n_chats=1, messages_per_chat=25)

    def new_message(m: AvitoMock, chat_id: str, offset: int) -> None:
        if offset > 0:
            m.add_message(chat_id, "Синтетическое новое сообщение")

    mock.on_messages_request = new_message
    async with make_client(mock) as client:
        pager = paginate_messages(client, U, CHAT, limit=10)
        ids = await _collect_ids(pager)
    assert pager.duplicates == 2  # one shifted entry per later page
    assert len(set(ids)) == 25  # original messages all seen; the new ones are ahead of offset 0
    assert pager.stop_reason is StopReason.SHORT_PAGE


@pytest.mark.parametrize("order", ["updated_desc", "updated_asc", "insertion"])
async def test_chats_pagination(order: str) -> None:
    mock = AvitoMock.with_synthetic_data(n_chats=12, messages_per_chat=1, chat_order=order)
    async with make_client(mock) as client:
        pager = paginate_chats(client, U, limit=5)
        ids = await _collect_ids(pager)
    assert sorted(ids) == sorted(mock.chats)
    assert pager.stop_reason is StopReason.SHORT_PAGE


async def test_invalid_limit_rejected_before_any_request() -> None:
    mock = AvitoMock.with_synthetic_data()
    async with make_client(mock) as client:
        pager = paginate_chats(client, U, limit=100)
        with pytest.raises(ValueError):
            await _collect_ids(pager)
    assert [r for r in mock.requests if r.endpoint == "chats_list"] == []
